
# 基准收益
bm_return_v <- function(stock.price, cash){
  bm.return <- cash * stock.price / stock.price[1]
  bm.return
}

# 收益率, 期末收益，日收益，年化收益
return_rate <- function(stock.price, type = 'raw', days = NA) {
  if (is.vector(stock.price) && is.numeric(stock.price)) {
    rate.raw <- last(stock.price)/stock.price[1] - 1
  } else {
    stop('none-numeric data input')
  }

  if (!(type %in% c('raw', 'day','year'))){
    stop('value of type must be one of c(\'raw\', \'day\', \'year\')')
  }

  if (is.integer(days) && days > 0) {
    rate.d <- (1 + rate.raw)^(1/days) - 1
  } else {
    if (type != 'raw') stop('value of days must be none-zero integer')
  }

  if (type == 'raw'){
    rate <- rate.raw
  } else if (type == 'day') {
    rate <- rate.d
  } else if (type == 'year'){
    rate <- (1 + rate.d)^(250) - 1
  }
  rate
}

# 日交易beta
beta_stock <- function(stock.price, cash.begin, total.price){
  cov(diff(stock.price)*(cash.begin/stock.price[1]), diff(total.price))/
    var(diff(stock.price)*(cash.begin/stock.price[1]))
}


# Alpha
#' @param stock.price vector of a stock price series, time level could be 1day, 1hour or 1min.
#' @param cash.begin cash used at begining of a trade
#' @param trade.value vector of a numeric series which represents the total value generated by a
#'    trade strategy correspond to stock.price.
#' @param rate risk free rate
#' @param trade.days time span of day

alpha_stock <- function(stock.price, cash.begin, trade.value, rate, trade.days){
  temp.beta <- beta_stock(stock.price, cash.begin, trade.value)
  benchmark.annual.return <- return_rate(stock.price, type = 'year', days = trade.days)
  strategy.annual.return <- return_rate(trade.value, type = 'year', days = trade.days)
  temp.alpha <- strategy.annual.return - (rate + beta*(benchmark.annual.return - rate))
  temp.alpha
}


#' Algorithm Volatility
#' @param trade.value vector of a numeric series which represents the total value generated by a
#'    trade strategy computed in daily.

algo_vol <- function(trade.value){
  # 用来测量策略的风险性，波动越大代表策略风险越高。
  alv <- sqrt(250*var(diff(trade.value)/trade.value[-length(trade.value)]))
  alv
}

#' Compute charpe ratio of the input trade.value
#' @param trade.value vector of a numeric series which represents the total value generated by a
#'    trade strategy.
#' @param rate risk free rate
#' @param trade.days time span of day
sharpe_rate <- function(trade.value, rate, trade.days){

  strategy.annual.return <- return_rate(trade.value, type = 'year', days = trade.days)
  alg.vol <- algo_vol(trade.value)
  sharpe <- (strategy.annual.return - rate)/alg.vol
  sharpe
}


info_rate <- function(stock.price, cash.begin, trade.value, trade.days){
  # 策略与基准每日收益差值的年化标准差
  strategy.benchmark.annual.sd <- sd(diff(stock.price[loc.day])*(cash.begin/stock.price[1]) -
                                       diff(trade.value[loc.day]))
  benchmark.annual.return <- return_rate(stock.price, type = 'year', days = trade.days)
  strategy.annual.return <- return_rate(trade.value, type = 'year', days = trade.days)
  info.ratio <- (strategy.annual.return - benchmark.annual.return)/strategy.benchmark.annual.sd
  info.ratio
}





